version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: infra/server/Dockerfile
      args:
        - GO_VERSION=${GO_VERSION}
    env_file:
      - ./../src/.env
      - ./.env
    depends_on:
      - mysql
      - redis
    ports:
      - "${API_PORT}:8080"
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -sf http://localhost:8080/healthz >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 5

  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"

  redis:
    image: redis:${REDIS_VERSION}
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
  redis_data:
